builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ws2connect
    binary: ws2connect
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarm:
      - 5
      - 6
      - 7
    flags:
      - -trimpath
snapcrafts:
  - name: ws2connect
    publish: true
    summary: CLI to expose TCP/TLS/UDP/UNIX service over websocket
    grade: devel
    confinement: strict
    base: core
    license: MPL-2.0
    description: |
      Expose any TCP service over websocket. Heavily inspired by socat and websocketd.

      * Single binary
      * Few resource consumption
      * Blazing fast
      * Supports multiple endpoints with multiple mappings
      * Supports dynamic and static endpoint mappings
      * Supports TLS (HTTPS) serving
      * Optional Basic or Digest authorization with encrypted (bcrypt or sha) httpasswd file as a secured storage
    apps:
      ws2connect:
        plugs: ['home', 'network', 'personal-files']

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^build:'