name: Build tools
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install tools
      env:
        SNAP_TOKEN: ${{ secrets.SNAP_TOKEN }}
      run: |
        sudo apt-get install -y curl snapcraft
        echo "${SNAP_TOKEN}" | snapcraft login --with -
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to bintray
      env:
        UPLOAD_BINTRAY_PASSWORD: ${{ secrets.UPLOAD_BINTRAY_PASSWORD }}
        DISTRIBUTION: "trusty,xenial,bionic,buster,wheezy"
        USERNAME: reddec
        PROJECT: "ws2connect"
      run: |
        for package in $(ls dist/*linux*.deb); do
          name=$(basename $package)
          component=$(echo $name | awk -F_  '{print $1}')
          arch=$(echo $package | sed s/.deb// | awk -F_  '{print $NF}')
          echo "component: $component; arch: $arch"
          curl -f -s -T "$package" -u "${USERNAME}:${UPLOAD_BINTRAY_PASSWORD}" "https://api.bintray.com/content/reddec/ws2connect-debian/${PROJECT}/${GITHUB_REF##*/}/${component}_${GITHUB_REF##*/}_${arch}.deb;publish=1;deb_component=main;deb_distribution=${DISTRIBUTION};deb_architecture=${arch}"
        done
        curl -X PATCH -f -s -H "Content-Type: application/json" -d  "{\"vcs_tag\" : \"${GITHUB_REF##*/}\", \"github_use_tag_release_notes\": true}" -u "${USERNAME}:${UPLOAD_BINTRAY_PASSWORD}" "https://api.bintray.com/packages/reddec/ws2connect-debian/${PROJECT}/versions/${GITHUB_REF##*/}"
